# Application Name
spring.application.name=sbadss

# Server Port
server.port=8080

# ======================
# PostgreSQL Database
# ======================
spring.datasource.url=jdbc:postgresql://localhost:5432/sbadss_db
spring.datasource.username=postgres
spring.datasource.password=asal2003
spring.datasource.driver-class-name=org.postgresql.Driver

# ======================
# JPA / Hibernate
# ======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ======================
# Optional (Good for debugging)
# ======================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE